//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Inspection_Machine_v3._0 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Contador : global::System.Configuration.ApplicationSettingsBase {
        
        private static Contador defaultInstance = ((Contador)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Contador())));
        
        public static Contador Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int ContadorE1 {
            get {
                return ((int)(this["ContadorE1"]));
            }
            set {
                this["ContadorE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ContadorE2 {
            get {
                return ((int)(this["ContadorE2"]));
            }
            set {
                this["ContadorE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ContadorX {
            get {
                return ((int)(this["ContadorX"]));
            }
            set {
                this["ContadorX"] = value;
            }
        }
    }
}
